language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
install:
- wget http://www.biicode.com/downloads/latest/ubuntu64
- mv ubuntu64 bii-ubuntu64.deb
- sudo dpkg -i bii-ubuntu64.deb && sudo apt-get -f install
- rm bii-ubuntu64.deb
- wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
- tar -xzf cmake-3.0.2-Linux-64.tar.gz
- sudo cp -fR cmake-3.0.2-Linux-64/* /usr
- rm -rf cmake-3.0.2-Linux-64
- rm cmake-3.0.2-Linux-64.tar.gz
script:
- cmake --version
- bii init biicode_project
- mkdir -p ./biicode_project/blocks/amalulla/bcl
- mv !(biicode_project) ./biicode_project/blocks/amalulla/bcl
- cd biicode_project
- bii find -um
- bii cpp:build
- "./bin/ && ls ./bin/amalulla_bcl_src_bfc"
after_success:
- bii user amalulla -p $BII_AMALULLA_PASSWORD
- bii publish --tag STABLE
